set nocompatible

" Vundle
    filetype off " required!

    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()

    " let Vundle manage Vundle
    " required! 
    Bundle 'gmarik/vundle'

    " My Bundles here:
    Bundle 'Align'
    Bundle 'Tabular'
    Bundle 'a.vim'
    Bundle 'surround.vim'
    Bundle 'minibufexpl.vim'
    Bundle 'taglist.vim'
    Bundle 'OmniCppComplete'
    Bundle 'vcscommand.vim'
    "Bundle'vimlatex'
    Bundle 'LaTeX-Box-Team/LaTeX-Box'
    Bundle 'Solarized'
    Bundle 'Zenburn'
    Bundle 'chriskempson/base16-vim'
    Bundle 'SudoEdit.vim'
    Bundle 'camelcasemotion'
    Bundle 'pyflakes.vim'
    Bundle 'pydoc.vim'
    Bundle 'snipMate'
" Vundle end

filetype plugin indent on

" Change leader from '\' to ,
"let mapleader = ","

" Columns
set columns=83 " +3 to account for the foldcolumns

" Color scheme and syntax highlighting
set background=dark
colorscheme solarized
syntax on

" Tabs and indent (python style)
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent

" Add system-wide tags
"set tags+=~/.vim/tags/c-local
" Add local include files to path
set path+=/usr/local/include
" Recursively set the path of the project.
set path+=$PWD/**

" Various options
set showcmd           " Show (partial) command in status line.
set showmatch         " Show matching brackets.
set ignorecase        " Do case insensitive matching
set smartcase         " Do smart case matching
set incsearch         " Incremental search
set autowrite         " Automatically save before commands like :next and :make
set autoread          " Automatically update file if changed on disk
set hidden            " Hide buffers when they are abandoned
set mouse=a           " Enable mouse usage (all modes)
set cursorline        " Highlight current line
set history=100       " Remember 100 lines of commands history
set virtualedit=block " Virtual edit in block visual mode
set diffopt+=vertical " Vertical diff

" Per-directory vimrc
set exrc
set secure

" Remove the icon bar from the GUI
set guioptions-=T
set guioptions-=m

" Wildcard completion menu
set wildmenu
set wildmode=longest,full

" Folding
set foldminlines=5 " Min number of lines for folding
"set foldopen=all
set foldnestmax=5

"TagList
let g:Tlist_Exit_OnlyWindow=1
noremap =<CR> :TlistToggle<CR>

" Auto close preview window
autocmd InsertLeave * if pumvisible() == 0|pclose|endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Macros
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" "Underline" with = signs
noremap y= yyp:s/./=/g<enter>
" Rebuild ctags database
noremap =t :!ctags -R --langmap=c:+.cu --c++-kinds=+pl --fields=+iaS --extra=+q .<CR>
" Decrease the number under cursor (C-A is reserved by screen)
nnoremap <C-e> <C-a>
" Search errors in quickfix window
nmap gb :copen<CR>/error:<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LATEX
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a single file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*

" VimLatex
" OPTIONAL: Starting with Vim 7, the filetype of empty .tex files defaults to
" 'plaintex' instead of 'tex', which results in vim-latex not being loaded.
" The following changes the default filetype back to 'tex':
let g:tex_flavor='latex'
let g:Tex_DefaultTargetFormat='pdf'
let g:Tex_GotoError=0
" Allow to type "é" with vimlatex
"imap <buffer> <leader>it <Plug>Tex_InsertItemOnThisLine

" LaTeX-box
"let g:LatexBox_latexmk_options='-pvc'
let g:LatexBox_Folding='yes'

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" C / C++ / CUDA
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Syntax based folding
autocmd FileType c,cpp,cuda setlocal foldmethod=syntax
autocmd FileType c,cpp,cuda setlocal foldcolumn=3
" .cuh as CUDA files
au BufEnter,BufNew *.cuh setlocal filetype=cuda
" GCC Compiler
compiler! gcc
" A.vim configuration
let g:alternateNoDefaultAlternate = 1
let g:alternateExtensions_cu = "h,cuh"
let g:alternateExtensions_h = "cu,c,cpp,cxx,cc,CC,cuh"
let g:alternateExtensions_cuh = "cu,c,cpp,cxx,cc,CC,h"
" CUDA TagList support
let tlist_cuda_settings= 'c++;n:namespace;v:variable;d:macro;t:typedef;' .
                             \ 'c:class;g:enum;s:struct;u:union;f:function'

