set nocompatible

" Vundle
    filetype off " required!

    set rtp+=~/.vim/bundle/vundle/
    call vundle#rc()

    " let Vundle manage Vundle
    " required!
    Bundle 'gmarik/vundle'

    " My Bundles here:
    " Editor
    Bundle 'a.vim'
    Bundle 'godlygeek/tabular'
    Bundle 'tpope/vim-surround'
    Bundle 'tpope/vim-repeat'
    Bundle 'tpope/vim-sleuth'
    Bundle 'mbbill/undotree'
    Bundle 'matchit.zip'
    Bundle 'maxbrunsfeld/vim-yankstack'
    call yankstack#setup() " Fix conflicts with vim-surround
    Bundle 'kien/rainbow_parentheses.vim'
    Bundle 'nathanaelkane/vim-indent-guides'
    let g:indent_guides_start_level=2
    Bundle 'terryma/vim-expand-region'
    " Files
    Bundle 'SudoEdit.vim'
    Bundle 'file-line'
    Bundle 'kien/ctrlp.vim'
    Bundle 'mhinz/vim-signify'
    Bundle 'vcscommand.vim'
    Bundle 'scrooloose/nerdtree'
    " Other utils
    Bundle 'tpope/vim-dispatch.git'
    Bundle 'bling/vim-bufferline'
    Bundle 'bling/vim-airline'
    let g:airline_powerline_fonts = 1
    Bundle 'edkolev/promptline.vim'
    " Programming
    Bundle 'majutsushi/tagbar'
    Bundle 'Valloric/YouCompleteMe'
    Bundle 'SirVer/ultisnips'
    Bundle 'honza/vim-snippets'
    Bundle 'scrooloose/syntastic'
    let g:syntastic_tex_chktex_args = '-n 1 -n 9 -n 15 -n 17 -n 22'
    Bundle 'tpope/vim-commentary'
    Bundle 'tpope/vim-endwise'
    Bundle 'rhysd/vim-clang-format'
    augroup ClangFormatSettings
      autocmd!
      " map to <Leader>cf in C++ code
      autocmd FileType c,cpp,objc,cuda nnoremap <buffer><Leader>cf :<C-u>.ClangFormat<CR>
      autocmd FileType c,cpp,objc,cuda vnoremap <buffer><Leader>cf :ClangFormat<CR>
      " if you install vim-operator-user
      "autocmd FileType c,cpp,objc map <buffer><Leader>x <Plug>(operator-clang-format)
    augroup end
    " Colorschemes / Appearance
    Bundle 'altercation/vim-colors-solarized'
    Bundle 'Zenburn'
    Bundle 'chriskempson/base16-vim'
    Bundle 'tomasr/molokai'
    Bundle 'bling/vim-airline'
    Bundle 'edkolev/promptline.vim'
    let g:airline_powerline_fonts = 1
" Vundle end
filetype plugin indent on

" Matchit plugin shipped with vim
runtime! macros/matchit.vim

" Change leader from '\' to ,
let mapleader = "\<Space>"
let maplocalleader = ","

" swap and backup files
set directory=~/.backup//

" Persistent undo
set undofile                " Save undo's after file closes
set undodir=~/.vim/undo     " where to save undo histories
nmap =u :UndotreeToggle<CR>

" Lines
set lines=100

" Columns
set colorcolumn=80

" Color scheme and syntax highlighting
set background=dark
" F5 swith between dark and light background
call togglebg#map("<F5>")
colorscheme solarized
" Solarized scheme on terminal needs only the 16-color palette
set t_Co=16

syntax on

" Status line
set laststatus=2
set ruler

" Tabs and indent (python style)
set shiftwidth=4
set tabstop=4
set expandtab
set autoindent

" Add system-wide tags
"set tags+=~/.vim/tags/c-local
" Add local include files to path
set path+=/usr/local/include
" Recursively set the path of the project.
set path+=$PWD/**

" Various options
set showcmd           " Show (partial) command in status line.
set showmatch         " Show matching brackets.
set ignorecase        " Do case insensitive matching
set smartcase         " Do smart case matching
set incsearch         " Incremental search
set autowrite         " Automatically save before commands like :next and :make
set autoread          " Automatically update file if changed on disk
set hidden            " Hide buffers when they are abandoned
set mouse=a           " Enable mouse usage (all modes)
set cursorline        " Highlight current line
set history=100       " Remember 100 lines of commands history
set virtualedit=block " Virtual edit in block visual mode
set diffopt+=vertical " Vertical diff
set scrolloff=10      " Minimum space between window border and cursor
set nojoinspaces      " Don't put double spaces when joining lines

" Toggle hlsearch
nnoremap <Leader>h :set hlsearch!<CR>

" Per-directory vimrc
set exrc
set secure

" Remove the icon bar from the GUI
set guioptions-=T
set guioptions-=m

" Wildcard completion menu
set wildmenu
set wildmode=longest,full

" Ignore these files when completing names and in Ex
set wildignore+=.svn,CVS,.git,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.xpm,*.gif,*.pdf,*.bak,*.aux,*.bbl
" Set of file name suffixes that will be given a lower priority when it comes to matching wildcards
set suffixes+=.old

" Folding
set foldminlines=10 " Min number of lines for folding
"set foldopen=all
set foldnestmax=3
set foldlevel=1

" Recursively open current fold and only it
nnoremap <Leader>x zxzczO

"TagBar
let g:tagbar_expand = 1
let g:tagbar_sort = 0
let g:tagbar_compact = 1
noremap =<CR> :TagbarToggle<CR>
let g:tagbar_left=1
" -- handle CUDA as C++
let g:tagbar_type_cuda = {
    \ 'ctagstype' : 'c++',
    \ 'kinds'     : [
        \ 'd:macros:1:0',
        \ 'p:prototypes:1:0',
        \ 'g:enums',
        \ 'e:enumerators:0:0',
        \ 't:typedefs:0:0',
        \ 'n:namespaces',
        \ 'c:classes',
        \ 's:structs',
        \ 'u:unions',
        \ 'f:functions',
        \ 'm:members:0:0',
        \ 'v:variables:0:0'
    \ ],
    \ 'sro'        : '::',
    \ 'kind2scope' : {
        \ 'g' : 'enum',
        \ 'n' : 'namespace',
        \ 'c' : 'class',
        \ 's' : 'struct',
        \ 'u' : 'union'
    \ },
    \ 'scope2kind' : {
        \ 'enum'      : 'g',
        \ 'namespace' : 'n',
        \ 'class'     : 'c',
        \ 'struct'    : 's',
        \ 'union'     : 'u'
    \ }
\ }

" Wrap by word
set wrap
set linebreak
set display=lastline

" Move through wrapped lines
inoremap <silent> <Down> <C-o>gj
inoremap <silent> <Up> <C-o>gk
noremap <silent> <Down> gj
noremap <silent> <Up> gk
noremap <silent> <M-j> gj
noremap <silent> <M-k> gk
noremap <silent> <M-h> h
noremap <silent> <M-l> l

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" CtrlP
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
if has("gui_running")
    let g:ctrlp_prompt_mappings = {
                \ 'ToggleType(1)':        ['<c-Space>', '<c-f>', '<c-up>'],
                \ }
else
    let g:ctrlp_prompt_mappings = {
                \ 'ToggleType(1)':        ['<Nul>', '<c-f>', '<c-up>'],
                \ }
endif
let g:ctrlp_extensions = ['mixed', 'buffertag', 'tag', 'line']
let g:ctrlp_cmd = 'CtrlPMixed'


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" YouCompleteMe
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" YCM/Ultisnips compatibility
let g:UltiSnipsExpandTrigger='<c-j>'
let g:UltiSnipsJumpBackwardTrigger='<up>'
let g:ycm_seed_identifiers_with_syntax = 1

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Macros
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" "Underline" with = signs
noremap y= yyp:s/./=/g<enter>
" Rebuild ctags database
noremap =t :!ctags -R --langmap=c:+.cu --c++-kinds=+pl --fields=+iaS --extra=+q .<CR>
" Decrease the number under cursor (C-A is reserved by screen)
nnoremap <C-e> <C-a>
" Search errors in quickfix window
noremap gb :copen<CR>/error:<CR>
" Switch buffers (for Putty sessions where std shortcut doesn't work)
nnoremap <C-b> :b#<CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" LATEX
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" IMPORTANT: grep will sometimes skip displaying the file name if you
" search in a single file. This will confuse Latex-Suite. Set your grep
" program to always generate a file-name.
set grepprg=grep\ -nH\ $*
" Surround.vim support for Latex commands
let g:surround_{char2nr('c')} = "\\\1command\1{\r}"
" Manual
au filetype tex setlocal makeprg=rubber\ --pdf\ --inplace\ -f\ %;\ rubber-info\ --check\ %
au filetype tex nnoremap <localleader>v :!xdg-open %<.pdf&<CR><CR>

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" C / C++ / CUDA
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
augroup CudaCommands
  autocmd!
  " Syntax based folding
  autocmd FileType c,cpp,cuda setlocal foldmethod=syntax
  autocmd FileType c,cpp,cuda setlocal foldcolumn=0
  " .cuh as CUDA files
  autocmd BufEnter,BufNew *.cuh setlocal filetype=cuda
  autocmd FileType cuda setlocal filetype=cuda.cpp
augroup end
" GCC Compiler
compiler! gcc
" A.vim configuration
let g:alternateNoDefaultAlternate = 1
let g:alternateExtensions_cu = "h,cuh"
let g:alternateExtensions_h = "cu,c,cpp,cxx,cc,CC,cuh"
let g:alternateExtensions_cuh = "cu,c,cpp,cxx,cc,CC,h"
augroup AlternateFix
  autocmd!
  autocmd VimEnter * unmap! <Leader>ih
  autocmd VimEnter * unmap! <Leader>is
  autocmd VimEnter * unmap! <Leader>ihn
augroup end
" CUDA TagList support
let tlist_cuda_settings= 'c++;n:namespace;v:variable;d:macro;t:typedef;' .
                             \ 'c:class;g:enum;s:struct;u:union;f:function'

