bindkey -e
bindkey  "^[[H"   beginning-of-line
bindkey  "^[[F"   end-of-line

autoload -U select-word-style
select-word-style bash

autoload -U history-search-end
zle -N history-beginning-search-backward-end history-search-end
zle -N history-beginning-search-forward-end history-search-end
bindkey "^[[A" history-beginning-search-backward-end
bindkey "^[[B" history-beginning-search-forward-end

# Enable Ctrl-x-e to edit command line
autoload -U edit-command-line
zle -N edit-command-line
bindkey '^xe' edit-command-line
bindkey '^x^e' edit-command-line

export PATH="/opt/homebrew/bin:$PATH"

fpath=($(brew --prefix)/share/zsh-completions $fpath)
autoload -U compinit && compinit

export EDITOR=nvim
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$(brew --prefix)/opt/llvm/bin:$PATH"
export PATH="$HOME/Library/Android/sdk/platform-tools:$PATH"

alias bbat="bat --theme=\$(defaults read -globalDomain AppleInterfaceStyle &> /dev/null && echo default || echo GitHub)"
export JAVA_HOME="$(brew --prefix)/opt/java11"

[[ -n $VIRTUAL_ENV && -e "${VIRTUAL_ENV}/bin/activate" ]] && source "${VIRTUAL_ENV}/bin/activate"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[[ -r "$HOME/.fzf.git.bash" ]] && . "$HOME/.fzf.git.bash"

setopt prompt_subst
. $(brew --prefix)/etc/bash_completion.d/git-prompt.sh
export RPROMPT=$'$(__git_ps1 "%s")'

precmd () {print -Pn "\e]0;%2~\a"}
eval "$(pyenv init -)"
